--- 
- hosts: mywebservers 
  become: yes
  tasks:
  - name: instal java on ubuntu
    apt:
      name: "{{myjavaonubuntu}}"
      state: present 
    when: ansible_os_family=="Debian"
  
  - name: instal java on redhat 
    dnf:
      name: "{{myjavaonredhat}}"
      state: present
    when: ansible_os_family=="RedHat"