---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: install webserver
      apt:
        name: "{{var01}}"
        state: present
      when: ansible_os_family =="Debian"
    - name: I want to start WebServer
      service:
        name: "{{var01}}"
        state: started
      when: ansible_os_family =="Debian"
 